apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant_app
  labels:
    app: tenant_app
#  namespace: dapr-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant_app
  template:
    metadata:
      labels:
        app: tenant_app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "tenant_app"
        dapr.io/app-port: "8000"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: tenant_app
        image: drf:latest
        env:
        - name: "APP_PORT"
          value: "8000"
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
