version: '3'

volumes:
  tenant_management_local_postgres_data_1: {}
  tenant_management_local_postgres_data_2: {}
  tenant_management_local_postgres_data_3: {}

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: neo_tenant_management:latest
    container_name: neo_tenant_management
    depends_on:
      - postgres1
      - postgres2
      - postgres3
    volumes:
      - .:/app:z
    ports:
      - '8000:8000'

  postgres1:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_1:/var/lib/postgresql/data
    env_file:
      - .env
  postgres2:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_2:/var/lib/postgresql/data
    env_file:
      - .env
  postgres3:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_3:/var/lib/postgresql/data
    env_file:
      - .env
