version: '3'

volumes:
  tenant_management_local_postgres_data_1: { }
  tenant_management_local_postgres_data_2: { }
  tenant_management_local_postgres_data_3: { }
  tenant_management_local_postgres_data_4: { }
  tenant_management_local_postgres_data_5: { }
  tenant_management_local_postgres_data_6: { }
  tenant_management_local_postgres_data_7: { }
  tenant_management_local_postgres_data_8: { }
  tenant_management_local_postgres_data_9: { }
  tenant_management_local_postgres_data_10: { }
  tenant_management_local_postgres_data_11: { }
  tenant_management_local_postgres_data_12: { }
  tenant_management_local_postgres_data_13: { }
  tenant_management_local_postgres_data_14: { }
  tenant_management_local_postgres_data_15: { }
  tenant_management_local_postgres_data_16: { }
  tenant_management_local_postgres_data_17: { }
  tenant_management_local_postgres_data_18: { }
  tenant_management_local_postgres_data_19: { }
  tenant_management_local_postgres_data_20: { }


services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: neo_tenant_management:latest
    container_name: neo_tenant_management
    depends_on:
      - postgres1
      - postgres2
      - postgres3
      - postgres4
      - postgres5
      - postgres6
      - postgres7
      - postgres8
      - postgres9
      - postgres10
      - postgres11
      - postgres12
      - postgres13
      - postgres14
      - postgres15
      - postgres16
      - postgres17
      - postgres18
      - postgres19
      - postgres20
    volumes:
      - .:/app:z
    ports:
      - '8000:8000'

  postgres1:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_1:/var/lib/postgresql/data
    env_file:
      - .env
  postgres2:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_2:/var/lib/postgresql/data
    env_file:
      - .env
  postgres3:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_3:/var/lib/postgresql/data
    env_file:
      - .env
  postgres4:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_4:/var/lib/postgresql/data
    env_file:
      - .env
  postgres5:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_5:/var/lib/postgresql/data
    env_file:
      - .env

  postgres6:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_6:/var/lib/postgresql/data
    env_file:
      - .env
  postgres7:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_7:/var/lib/postgresql/data
    env_file:
      - .env
  postgres8:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_8:/var/lib/postgresql/data
    env_file:
      - .env
  postgres9:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_9:/var/lib/postgresql/data
    env_file:
      - .env
  postgres10:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_10:/var/lib/postgresql/data
    env_file:
      - .env
  postgres11:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_11:/var/lib/postgresql/data
    env_file:
      - .env
  postgres12:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_12:/var/lib/postgresql/data
    env_file:
      - .env
  postgres13:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_13:/var/lib/postgresql/data
    env_file:
      - .env
  postgres14:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_14:/var/lib/postgresql/data
    env_file:
      - .env
  postgres15:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_15:/var/lib/postgresql/data
    env_file:
      - .env
  postgres16:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_16:/var/lib/postgresql/data
    env_file:
      - .env

  postgres17:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_17:/var/lib/postgresql/data
    env_file:
      - .env

  postgres18:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_18:/var/lib/postgresql/data
    env_file:
      - .env

  postgres19:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_19:/var/lib/postgresql/data
    env_file:
      - .env

  postgres20:
    image: postgres:15
    volumes:
      - tenant_management_local_postgres_data_20:/var/lib/postgresql/data
    env_file:
      - .env
