# Generated by Django 4.2.5 on 2023-10-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
