# Generated by Django 4.2.5 on 2023-10-19 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_tenant_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="email",
        ),
    ]
