# Generated by Django 4.2.5 on 2023-10-31 05:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_tenant_email"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tenant",
            new_name="Employee",
        ),
    ]
