# Generated by Django 4.2.5 on 2023-10-31 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_tenant_delete_employee"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tenant",
            new_name="Employee",
        ),
    ]
